{% set name = "snowpark-connect-deps-2" %}
{% set version = "3.56.7" %}
{% set python_min = "3.10" %}
{% set python_max = "3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/snowpark_connect_deps_2-{{ version }}.tar.gz
  sha256: ded0cdde2c6da769a06ccd30c3d98793f1715da9e07f04e2fc1298299f39cf77

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<{{ python_max }}

test:
  imports:
    - snowpark_connect_deps_2
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://www.snowflake.com
  summary: Supporting JAR dependencies for Snowpark Connect (Part 2)
  license: Apache-2.0
  license_file:
    - LICENSE-binary
    - NOTICE-binary
    - LICENSE.txt

extra:
  recipe-maintainers:
    - sfc-gh-manowotka
    - sfc-gh-azhan
    - sfc-gh-ckonigsmark
    - sfc-gh-igarish
    - sfc-gh-kgadomski
    - sfc-gh-pwojcik
    - sfc-gh-saroskar
    - sfc-gh-skumbham
